owner: surukotonai
repo: nautrestatus

sites:
  - name: Nature
    url: https://natureclient.com/
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    
  - name: NatureApi
    url: https://natureclient.com:2053/status
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

status-website:
  baseUrl: /nautrestatus
  name: Nature Client Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/3 * * * *"
