owner: surukotonai
repo: nautrestatus

sites:
  - name: Nature
    url: https://natureclient.com/
    
  - name: NatureApi
    url: https://natureclient.com:2053/status

status-website:
  baseUrl: /nautrestatus
  name: Nature Client Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/3 * * * *"
