owner: surukotonai
repo: nautrestatus

sites:
  - name: Nature
    url: https://natureclient.com/
    headers:
      - "User-Agent: fat/1.0"
      - "fat: lawl"
  - name: NatureApi
    url: https://natureclient.com:2053/status
    headers:
      - "User-Agent: fat/1.0"
      - "fat: lawl"

status-website:
  baseUrl: /nautrestatus
  name: Nature Client Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
workflowSchedule:
  uptime: "*/5 * * * *"
